use crate::aabb::AABB;
use crate::bvh::BVHNode;
use crate::constant_medium::ConstantMedium;
use crate::hittable::{Hittable, RotateY, Translate};
use crate::hittable_list::HittableList;
use crate::material::{Dielectric, DiffuseLight, Isotropic, Lambertian, Material, Metal};
use crate::quad::Quad;
use crate::sphere::Sphere;
use crate::texture::{CheckerTexture, ImageTexture, NoiseTexture, SolidColor, Texture};
use crate::triangle::Triangle;
use crate::{Color, Point3, Vec3};

use std::collections::HashMap;
use std::fs;
use std::path::Path;
use std::sync::Arc;

// Generated by GPT-5.3-Codex.

#[derive(Clone, Copy)]
struct Transform {
    m: [[f64; 3]; 3],
    t: Vec3,
}

impl Transform {
    fn identity() -> Self {
        Self {
            m: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
            t: Vec3::new(0.0, 0.0, 0.0),
        }
    }

    fn rotate_y(cos_theta: f64, sin_theta: f64) -> Self {
        Self {
            m: [
                [cos_theta, 0.0, sin_theta],
                [0.0, 1.0, 0.0],
                [-sin_theta, 0.0, cos_theta],
            ],
            t: Vec3::new(0.0, 0.0, 0.0),
        }
    }

    fn translate(offset: Vec3) -> Self {
        Self {
            m: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
            t: offset,
        }
    }

    fn apply_vec(&self, v: Vec3) -> Vec3 {
        let (x, y, z) = v.components();
        Vec3::new(
            self.m[0][0] * x + self.m[0][1] * y + self.m[0][2] * z,
            self.m[1][0] * x + self.m[1][1] * y + self.m[1][2] * z,
            self.m[2][0] * x + self.m[2][1] * y + self.m[2][2] * z,
        )
    }

    fn apply_point(&self, p: Point3) -> Point3 {
        self.apply_vec(p) + self.t
    }

    fn compose(&self, local: Transform) -> Transform {
        let mut m = [[0.0; 3]; 3];
        for i in 0..3 {
            for j in 0..3 {
                m[i][j] = self.m[i][0] * local.m[0][j]
                    + self.m[i][1] * local.m[1][j]
                    + self.m[i][2] * local.m[2][j];
            }
        }
        let t = self.apply_vec(local.t) + self.t;
        Transform { m, t }
    }
}

#[derive(Clone)]
struct TextureRow {
    type_id: i32,
    c1: Color,
    c2: Color,
    c3: Color,
    resource_id: i32,
}

#[derive(Clone)]
struct MaterialRow {
    type_id: i32,
    texture_id: i32,
    color: Color,
    p1: f64,
    p2: f64,
}

#[derive(Clone)]
struct HittableRow {
    type_id: i32,
    p: Vec3,
    u: Vec3,
    v: Vec3,
    moving: Vec3,
    aux1: Vec3,
    aux2: Vec3,
    radius: f64,
    texture_id: i32,
    material_id: i32,
    bbox: AABB,
}

#[derive(Clone)]
struct BvhRow {
    left: i32,
    right: i32,
    bbox: AABB,
    hittable_index: i32,
}

#[derive(Clone)]
struct ResourceRow {
    type_id: i32,
    path: String,
}

#[derive(Default)]
struct IrContext {
    textures: Vec<TextureRow>,
    materials: Vec<MaterialRow>,
    hittables: Vec<HittableRow>,
    bvh: Vec<BvhRow>,
    resources: Vec<ResourceRow>,
    texture_map: HashMap<usize, i32>,
    material_map: HashMap<usize, i32>,
    resource_map: HashMap<String, i32>,
}

fn arc_key<T: ?Sized>(arc: &Arc<T>) -> usize {
    Arc::as_ptr(arc) as *const () as usize
}

fn vec3_zero() -> Vec3 {
    Vec3::new(0.0, 0.0, 0.0)
}

fn bbox_from_points(points: &[Point3]) -> AABB {
    let mut min = Point3::new(f64::INFINITY, f64::INFINITY, f64::INFINITY);
    let mut max = Point3::new(f64::NEG_INFINITY, f64::NEG_INFINITY, f64::NEG_INFINITY);
    for p in points {
        min[0] = min[0].min(p[0]);
        min[1] = min[1].min(p[1]);
        min[2] = min[2].min(p[2]);
        max[0] = max[0].max(p[0]);
        max[1] = max[1].max(p[1]);
        max[2] = max[2].max(p[2]);
    }
    AABB::from_points(min, max)
}

fn encode_texture(ctx: &mut IrContext, tex: Arc<dyn Texture>) -> Result<i32, String> {
    let key = arc_key(&tex);
    if let Some(id) = ctx.texture_map.get(&key) {
        return Ok(*id);
    }

    let id = ctx.textures.len() as i32;
    let any = tex.as_any();

    let row = if let Some(solid) = any.downcast_ref::<SolidColor>() {
        TextureRow {
            type_id: 1,
            c1: solid.albedo(),
            c2: vec3_zero(),
            c3: vec3_zero(),
            resource_id: 0,
        }
    } else if let Some(checker) = any.downcast_ref::<CheckerTexture>() {
        let odd = checker.odd();
        let even = checker.even();
        let odd_solid = odd
            .as_any()
            .downcast_ref::<SolidColor>()
            .ok_or_else(|| "CheckerTexture odd texture must be SolidColor in IR".to_string())?;
        let even_solid = even
            .as_any()
            .downcast_ref::<SolidColor>()
            .ok_or_else(|| "CheckerTexture even texture must be SolidColor in IR".to_string())?;
        TextureRow {
            type_id: 2,
            c1: odd_solid.albedo(),
            c2: even_solid.albedo(),
            c3: Vec3::new(checker.inv_scale(), 0.0, 0.0),
            resource_id: 0,
        }
    } else if let Some(image) = any.downcast_ref::<ImageTexture>() {
        let path = image.path().to_string();
        let rid = if let Some(rid) = ctx.resource_map.get(&path) {
            *rid
        } else {
            let rid = ctx.resources.len() as i32;
            ctx.resources.push(ResourceRow {
                type_id: 1,
                path: path.clone(),
            });
            ctx.resource_map.insert(path, rid);
            rid
        };
        TextureRow {
            type_id: 3,
            c1: vec3_zero(),
            c2: vec3_zero(),
            c3: vec3_zero(),
            resource_id: rid,
        }
    } else if any.downcast_ref::<NoiseTexture>().is_some() {
        TextureRow {
            type_id: 4,
            c1: vec3_zero(),
            c2: vec3_zero(),
            c3: vec3_zero(),
            resource_id: 0,
        }
    } else {
        return Err("Unsupported Texture type for IR export".to_string());
    };

    ctx.textures.push(row);
    ctx.texture_map.insert(key, id);
    Ok(id)
}

fn encode_material(ctx: &mut IrContext, mat: Arc<dyn Material>) -> Result<(i32, i32), String> {
    let key = arc_key(&mat);
    if let Some(id) = ctx.material_map.get(&key) {
        let row = &ctx.materials[*id as usize];
        return Ok((row.texture_id, *id));
    }

    let id = ctx.materials.len() as i32;
    let any = mat.as_any();

    let row = if let Some(lambertian) = any.downcast_ref::<Lambertian>() {
        let tex_id = encode_texture(ctx, lambertian.texture())?;
        MaterialRow {
            type_id: 1,
            texture_id: tex_id,
            color: vec3_zero(),
            p1: 0.0,
            p2: 0.0,
        }
    } else if let Some(metal) = any.downcast_ref::<Metal>() {
        MaterialRow {
            type_id: 2,
            texture_id: 0,
            color: metal.albedo(),
            p1: metal.fuzz(),
            p2: 0.0,
        }
    } else if let Some(dielectric) = any.downcast_ref::<Dielectric>() {
        MaterialRow {
            type_id: 3,
            texture_id: 0,
            color: vec3_zero(),
            p1: dielectric.refractive_index(),
            p2: 0.0,
        }
    } else if let Some(light) = any.downcast_ref::<DiffuseLight>() {
        let tex_id = encode_texture(ctx, light.texture())?;
        MaterialRow {
            type_id: 4,
            texture_id: tex_id,
            color: vec3_zero(),
            p1: 0.0,
            p2: 0.0,
        }
    } else if let Some(isotropic) = any.downcast_ref::<Isotropic>() {
        let tex_id = encode_texture(ctx, isotropic.texture())?;
        MaterialRow {
            type_id: 5,
            texture_id: tex_id,
            color: vec3_zero(),
            p1: 0.0,
            p2: 0.0,
        }
    } else {
        return Err("Unsupported Material type for IR export".to_string());
    };

    ctx.materials.push(row.clone());
    ctx.material_map.insert(key, id);
    Ok((row.texture_id, id))
}

fn push_sphere(ctx: &mut IrContext, sphere: &Sphere, xf: Transform) -> Result<(), String> {
    let center_ray = sphere.center_ray();
    let center0 = xf.apply_point(*center_ray.origin());
    let moving = xf.apply_vec(*center_ray.direction());
    let center1 = center0 + moving;
    let r = sphere.radius();
    let rv = Vec3::new(r, r, r);
    let bbox = AABB::from_aabbs(
        &AABB::from_points(center0 - rv, center0 + rv),
        &AABB::from_points(center1 - rv, center1 + rv),
    );
    let (texture_id, material_id) = encode_material(ctx, sphere.material())?;
    ctx.hittables.push(HittableRow {
        type_id: 1,
        p: center0,
        u: vec3_zero(),
        v: vec3_zero(),
        moving,
        aux1: vec3_zero(),
        aux2: vec3_zero(),
        radius: r,
        texture_id,
        material_id,
        bbox,
    });
    Ok(())
}

fn push_triangle(ctx: &mut IrContext, tri: &Triangle, xf: Transform) -> Result<(), String> {
    let a = xf.apply_point(tri.a());
    let e1 = xf.apply_vec(tri.edge1());
    let e2 = xf.apply_vec(tri.edge2());
    let b = a + e1;
    let c = a + e2;
    let bbox = bbox_from_points(&[a, b, c]);
    let (texture_id, material_id) = encode_material(ctx, tri.material())?;
    ctx.hittables.push(HittableRow {
        type_id: 2,
        p: a,
        u: e1,
        v: e2,
        moving: vec3_zero(),
        aux1: vec3_zero(),
        aux2: vec3_zero(),
        radius: 0.0,
        texture_id,
        material_id,
        bbox,
    });
    Ok(())
}

fn push_quad(ctx: &mut IrContext, quad: &Quad, xf: Transform) -> Result<(), String> {
    let q = xf.apply_point(quad.q());
    let u = xf.apply_vec(quad.u());
    let v = xf.apply_vec(quad.v());
    let w = xf.apply_vec(quad.w());
    let p1 = q;
    let p2 = q + u;
    let p3 = q + v;
    let p4 = p2 + v;
    let bbox = bbox_from_points(&[p1, p2, p3, p4]);
    let (texture_id, material_id) = encode_material(ctx, quad.material())?;
    ctx.hittables.push(HittableRow {
        type_id: 3,
        p: q,
        u,
        v,
        moving: vec3_zero(),
        aux1: w,
        aux2: vec3_zero(),
        radius: 0.0,
        texture_id,
        material_id,
        bbox,
    });
    Ok(())
}

fn collect_hittables(ctx: &mut IrContext, obj: &dyn Hittable, xf: Transform) -> Result<(), String> {
    let any = obj.as_any();

    if let Some(sphere) = any.downcast_ref::<Sphere>() {
        return push_sphere(ctx, sphere, xf);
    }
    if let Some(triangle) = any.downcast_ref::<Triangle>() {
        return push_triangle(ctx, triangle, xf);
    }
    if let Some(quad) = any.downcast_ref::<Quad>() {
        return push_quad(ctx, quad, xf);
    }
    if let Some(list) = any.downcast_ref::<HittableList>() {
        for object in &list.objects {
            collect_hittables(ctx, object.as_ref(), xf)?;
        }
        return Ok(());
    }
    if let Some(bvh) = any.downcast_ref::<BVHNode>() {
        let left = bvh.left();
        let right = bvh.right();
        collect_hittables(ctx, left.as_ref(), xf)?;
        collect_hittables(ctx, right.as_ref(), xf)?;
        return Ok(());
    }
    if let Some(translate) = any.downcast_ref::<Translate>() {
        let next = xf.compose(Transform::translate(translate.offset()));
        let child = translate.object();
        return collect_hittables(ctx, child.as_ref(), next);
    }
    if let Some(rotate) = any.downcast_ref::<RotateY>() {
        let next = xf.compose(Transform::rotate_y(rotate.cos_theta(), rotate.sin_theta()));
        let child = rotate.object();
        return collect_hittables(ctx, child.as_ref(), next);
    }
    if let Some(medium) = any.downcast_ref::<ConstantMedium>() {
        let boundary = medium.boundary();
        return collect_hittables(ctx, boundary.as_ref(), xf);
    }

    Err("Unsupported Hittable type for IR export".to_string())
}

#[derive(Clone)]
struct BvhBuildNode {
    bbox: AABB,
    left: Option<Box<BvhBuildNode>>,
    right: Option<Box<BvhBuildNode>>,
    hittable_index: Option<usize>,
}

fn build_bvh_tree(hittables: &[HittableRow], indices: &mut [usize]) -> BvhBuildNode {
    if indices.len() == 1 {
        let i = indices[0];
        return BvhBuildNode {
            bbox: hittables[i].bbox.clone(),
            left: None,
            right: None,
            hittable_index: Some(i),
        };
    }

    let mut bbox = AABB::EMPTY;
    for idx in indices.iter() {
        bbox = AABB::from_aabbs(&bbox, &hittables[*idx].bbox);
    }

    let axis = bbox.longest_axis() as usize;
    indices.sort_unstable_by(|a, b| {
        let ia = hittables[*a].bbox.axis_interval(axis as i32).min;
        let ib = hittables[*b].bbox.axis_interval(axis as i32).min;
        ia.total_cmp(&ib)
    });

    let mid = indices.len() / 2;
    let (left_indices, right_indices) = indices.split_at_mut(mid);
    let left_node = build_bvh_tree(hittables, left_indices);
    let right_node = build_bvh_tree(hittables, right_indices);

    let node_bbox = AABB::from_aabbs(&left_node.bbox, &right_node.bbox);
    BvhBuildNode {
        bbox: node_bbox,
        left: Some(Box::new(left_node)),
        right: Some(Box::new(right_node)),
        hittable_index: None,
    }
}

fn flatten_bvh(ctx: &mut IrContext, node: &BvhBuildNode) -> i32 {
    let idx = ctx.bvh.len() as i32;
    ctx.bvh.push(BvhRow {
        left: -1,
        right: -1,
        bbox: node.bbox.clone(),
        hittable_index: node.hittable_index.map(|x| x as i32).unwrap_or(-1),
    });

    if let Some(left) = &node.left {
        let left_idx = flatten_bvh(ctx, left);
        ctx.bvh[idx as usize].left = left_idx;
    }
    if let Some(right) = &node.right {
        let right_idx = flatten_bvh(ctx, right);
        ctx.bvh[idx as usize].right = right_idx;
    }

    idx
}

fn format_vec3(v: Vec3) -> String {
    format!("{} {} {}", v.x(), v.y(), v.z())
}

pub fn export_to_ir_string(root: &dyn Hittable) -> Result<String, String> {
    let mut ctx = IrContext::default();
    collect_hittables(&mut ctx, root, Transform::identity())?;

    if ctx.hittables.is_empty() {
        return Err("No hittables exported".to_string());
    }

    let mut indices: Vec<usize> = (0..ctx.hittables.len()).collect();
    let tree = build_bvh_tree(&ctx.hittables, &mut indices);
    flatten_bvh(&mut ctx, &tree);

    let mut out = String::new();

    out.push_str("TEXTURE\n");
    out.push_str(&format!("SIZE = {}\n", ctx.textures.len()));
    for t in &ctx.textures {
        out.push_str(&format!(
            "{} {} {} {} {}\n",
            t.type_id,
            format_vec3(t.c1),
            format_vec3(t.c2),
            format_vec3(t.c3),
            t.resource_id
        ));
    }

    out.push_str("MATERIAL\n");
    out.push_str(&format!("SIZE = {}\n", ctx.materials.len()));
    for m in &ctx.materials {
        out.push_str(&format!(
            "{} {} {} {} {}\n",
            m.type_id,
            m.texture_id,
            format_vec3(m.color),
            m.p1,
            m.p2
        ));
    }

    out.push_str("HITTABLE\n");
    out.push_str(&format!("SIZE = {}\n", ctx.hittables.len()));
    for h in &ctx.hittables {
        out.push_str(&format!(
            "{} {} {} {} {} {} {} {} {}\n",
            h.type_id,
            format_vec3(h.p),
            format_vec3(h.u),
            format_vec3(h.v),
            format_vec3(h.moving),
            format_vec3(h.aux1),
            format_vec3(h.aux2),
            h.radius,
            format!("{} {}", h.texture_id, h.material_id)
        ));
    }

    out.push_str("BVH\n");
    out.push_str(&format!("SIZE = {}\n", ctx.bvh.len()));
    for b in &ctx.bvh {
        out.push_str(&format!(
            "{} {} {} {} {} {} {} {} {}\n",
            b.left,
            b.right,
            b.bbox.x.min,
            b.bbox.x.max,
            b.bbox.y.min,
            b.bbox.y.max,
            b.bbox.z.min,
            b.bbox.z.max,
            b.hittable_index
        ));
    }

    out.push_str("RESOURCE\n");
    out.push_str(&format!("SIZE = {}\n", ctx.resources.len()));
    for r in &ctx.resources {
        out.push_str(&format!("{} {}\n", r.type_id, r.path));
    }

    Ok(out)
}

pub fn export_to_ir_file(root: &dyn Hittable, path: &str) -> Result<(), String> {
    let text = export_to_ir_string(root)?;
    let p = Path::new(path);
    if let Some(parent) = p.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    fs::write(p, text).map_err(|e| e.to_string())
}

#[derive(Default)]
pub struct ParsedIr {
    pub texture_count: usize,
    pub material_count: usize,
    pub hittable_count: usize,
    pub bvh_count: usize,
    pub resource_count: usize,
}

pub fn parse_ir_text(text: &str) -> Result<ParsedIr, String> {
    let mut lines = text.lines();

    fn read_section(lines: &mut std::str::Lines<'_>, name: &str) -> Result<usize, String> {
        let header = lines
            .next()
            .ok_or_else(|| format!("Missing section header {name}"))?;
        if header.trim() != name {
            return Err(format!("Expected section {name}, got {header}"));
        }
        let size_line = lines
            .next()
            .ok_or_else(|| format!("Missing SIZE line for {name}"))?;
        let (_, rhs) = size_line
            .split_once('=')
            .ok_or_else(|| format!("Invalid SIZE line for {name}"))?;
        let size = rhs.trim().parse::<usize>().map_err(|e| e.to_string())?;
        for _ in 0..size {
            lines
                .next()
                .ok_or_else(|| format!("Missing body line for {name}"))?;
        }
        Ok(size)
    }

    let texture_count = read_section(&mut lines, "TEXTURE")?;
    let material_count = read_section(&mut lines, "MATERIAL")?;
    let hittable_count = read_section(&mut lines, "HITTABLE")?;
    let bvh_count = read_section(&mut lines, "BVH")?;
    let resource_count = read_section(&mut lines, "RESOURCE")?;

    Ok(ParsedIr {
        texture_count,
        material_count,
        hittable_count,
        bvh_count,
        resource_count,
    })
}
